### ISSUE TITLE
Schema Checking

### ISSUE THREAD

**Issue by xenoscr** [LOLBAS-Project/LOLBAS#250]
# Schema Checking Action

I have implemented this in my own fork. it was something I started some time ago and appears the @wietze has implemented the "fixed" version of the YAML Schema checking action in his own repository. The issue with implementing it here is that our files have an additional "---" at the end of them denoting a new YAML entry. The solution would seem to remove the extra "---" from the end of each Yaml file. The Schema check errors out like this, note the error "expected a single document in the stream  in "<path>", line 2, column 1 but found another document":

```
=====================================
= Linting YAML files with pyKwalify =
=====================================
 INFO - linting yml/OSBinaries/AppInstaller.yml
Traceback (most recent call last):
  File "/usr/local/bin/pykwalify", line [8](https://github.com/xenoscr/LOLBAS-1/runs/8287881177?check_suite_focus=true#step:4:9), in <module>
    sys.exit(cli_entrypoint())
  File "/usr/local/lib/python3.[9](https://github.com/xenoscr/LOLBAS-1/runs/8287881177?check_suite_focus=true#step:4:10)/site-packages/pykwalify/cli.py", line 98, in cli_entrypoint
    run(parse_cli())
  File "/usr/local/lib/python3.9/site-packages/pykwalify/cli.py", line 76, in run
    c = Core(
  File "/usr/local/lib/python3.9/site-packages/pykwalify/core.py", line [10](https://github.com/xenoscr/LOLBAS-1/runs/8287881177?check_suite_focus=true#step:4:11)0, in __init__
    self.source = yml.load(stream)
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line [11](https://github.com/xenoscr/LOLBAS-1/runs/8287881177?check_suite_focus=true#step:4:12)9, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 81, in get_single_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "yml/OSBinaries/AppInstaller.yml", line 2, column 1
but found another document
  in "yml/OSBinaries/AppInstaller.yml", line [23](https://github.com/xenoscr/LOLBAS-1/runs/8287881177?check_suite_focus=true#step:4:24), column 1
```

**Comment by xenoscr** [comment]
Schema checks have been added to the workflows.
